version: 2.1
orbs:
  maven: circleci/maven@0.0.8
executors:
  my-executor:
    docker:
      - image: 'circleci/openjdk:11.0.1-jdk-stretch'
workflows:
  maven_test:
    jobs:
      - maven/test:
          settings_file: settings.xml
         executor: my-executor


